version: 0.1-{build}

environment:
  INTELOCLSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\5.3

image: Visual Studio 2017

configuration: Release

branches:
  only:
  - master

shallow_clone: true

# vcpkg enet, imgui are already available, but no on appveyor yet
# assimp, qt5 don't build
#  lua glm glslang gtest curl libuv zlib
before_build:
  - vcpkg install libpq
  # Install OpenCL headers and libraries
  - set NUGETDIR=C:\NUGET
  - nuget install opencl-nug -Version 0.777.77 -OutputDirectory %NUGETDIR%
  - dir %NUGETDIR%\opencl-nug.0.777.77\build\native\
  - set OCL_ROOT=%NUGETDIR%\opencl-nug.0.777.77\build\native
  # Install OpenCL Runtime
  - choco install opencl-intel-cpu-runtime
  # Check if it's working
  - ps: appveyor DownloadFile "https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform:+x64" -FileName clinfo.exe
  - .\clinfo.exe

build_script:
  - md build
  - cd build
  - cmake .. -DDISABLE_UNITY=On
  - cmake --build .
  - dir

artifacts:
  - name: Tests
    path: build/vengi-tests-core.exe

services:
  - postgresql          # start PostgreSQL 9.5 service

test_script:
  - cmd: build/vengi-tests-core.exe --gtest_output=xml:tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
